# Generated by Django 5.2.5 on 2025-11-11 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('cid', models.IntegerField(primary_key=True, serialize=False)),
                ('cname', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=10)),
                ('DOB', models.DateField()),
                ('phno', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('state', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
            ],
        ),
    ]
