# Generated by Django 5.2.5 on 2025-11-11 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('username', models.CharField(primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='register',
            name='password',
            field=models.CharField(default=1234, max_length=20),
            preserve_default=False,
        ),
    ]
