# Generated by Django 5.2.5 on 2025-11-14 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_login_register_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('mid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('cost', models.IntegerField()),
                ('expiry', models.DateField()),
                ('usage', models.TextField()),
                ('dosage', models.TextField()),
                ('image', models.ImageField(upload_to='meds/')),
            ],
        ),
        migrations.CreateModel(
            name='operator',
            fields=[
                ('opid', models.IntegerField(max_length=20, primary_key=True, serialize=False)),
                ('uname', models.CharField(max_length=20)),
                ('pwd', models.CharField(max_length=10)),
                ('g', models.CharField(max_length=10)),
                ('phno', models.IntegerField(max_length=10)),
            ],
        ),
    ]
