# Generated by Django 5.2.5 on 2025-11-14 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_bill_medicine_operator'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='mname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
