# Generated by Django 5.2.5 on 2025-11-14 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_bill_mname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='mname',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
