# Generated by Django 5.2.5 on 2025-11-14 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_alter_bill_mname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='mname',
        ),
    ]
