# Generated by Django 5.2.5 on 2025-11-14 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0006_remove_bill_mname'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='mname',
            field=models.CharField(default='', max_length=50),
        ),
    ]
