# Generated by Django 5.2.5 on 2025-11-14 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0007_bill_mname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='mname',
            field=models.CharField(default='unknown', max_length=50),
        ),
    ]
